.\" Manpage for seafile-client
.\" Contact freeplant@gmail.com to correct errors or typos.
.TH seafile 1 "31 Jan 2013" "Linux" "seafile client man page"
.SH NAME
ccnet \- the networking daemon of seafile client
.SH SYNOPSIS
ccnet [OPTIONS]
.SH DESCRIPTION
.BR ccnet
is the networking daemon of seafile client. It handles the identification and
communication with seafile server.
It's started by seafile-applet(1).
.SH SEE ALSO
seafile-applet(1), seaf-daemon(1), seafile-web(1), seaf-cli(1)
.SH AUTHOR
Lingtao Pan (freeplant@gmail.com)
.SH WEBSTIE
http://www.seafile.com
.LP
https://github.com/haiwen/seafile/
