.\" Manpage for seafile-client
.\" Contact freeplant@gmail.com to correct errors or typos.
.TH seafile 1 "31 Jan 2013" "Linux" "seafile-client man page"
.SH NAME
seafile-applet \- start the seafile client
.SH SYNOPSIS
seafile-applet [OPTIONS]
.SH DESCRIPTION
.BR seafile-applet
is the client program of seafile. It will start
.BR ccnet(1)
, 
.BR seaf-daemon(1)
, 
.BR seafile-web(1)
for you
.SH SEE ALSO
ccnet(1), seaf-daemon(1), seafile-web(1), seaf-cli(1)
.SH AUTHOR
Lingtao Pan (freeplant@gmail.com)
.SH WEBSTIE
http://www.seafile.com
.LP
https://github.com/haiwen/seafile/
