.\" Manpage for seafile-client
.\" Contact freeplant@gmail.com to correct errors or typos.
.TH seafile 1 "31 Jan 2013" "Linux" "seafile client man page"
.SH NAME
seaf-cli \- the command line interface for seafile client
.SH SYNOPSIS
seaf-cli [OPTIONS]
.SH DESCRIPTION
.BR seaf-cli
is the command line interface for seafile client.
.SH SEE ALSO
ccnet(1), seafile-applet(1), seaf-daemon(1), seafile-web(1)
.SH AUTHOR
Lingtao Pan (freeplant@gmail.com)
.SH WEBSTIE
http://www.seafile.com
.LP
https://github.com/haiwen/seafile/
