.\" Manpage for seafile-client
.\" Contact freeplant@gmail.com to correct errors or typos.
.TH seafile 1 "31 Jan 2013" "Linux" "seafile client man page"
.SH NAME
seaf-daemon \- the daemon of seafile client
.SH SYNOPSIS
seaf-daemon [OPTIONS]
.SH DESCRIPTION
.BR seafile-daemon
is the daemon of seafile client.
It's started by seafile-applet(1).
.SH SEE ALSO
ccnet(1), seaf-web(1), seafile-applet(1), seaf-cli(1)
.SH AUTHOR
Lingtao Pan (freeplant@gmail.com)
.SH WEBSTIE
http://www.seafile.com
.LP
https://github.com/haiwen/seafile/
