#ifndef HTTP_STATUS_CODES_H
#define HTTP_STATUS_CODES_H

/* Seafile specific http status codes. */

#define SEAF_HTTP_RES_BADFILENAME 440
#define SEAF_HTTP_RES_EXISTS 441
#define SEAF_HTTP_RES_NOT_EXISTS 441
#define SEAF_HTTP_RES_TOOLARGE 442
#define SEAF_HTTP_RES_NOQUOTA 443
#define SEAF_HTTP_RES_REPO_DELETED 444
#define SEAF_HTTP_RES_REPO_CORRUPTED 445
#define SEAF_HTTP_RES_BLOCK_MISSING 446


#endif
