#!/usr/bin/env python
# encoding: utf-8

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
import shutil


from setuptools import setup

targetfile = "ccnetweb.py"

APP = [targetfile]
DATA_FILES = []
PACKAGES = []
INCLUDES = ["utils"]
EXCLUDES = ["local_settings"]
PLIST = {"LSBackgroundOnly":True,
         "CFBundleIdentifier":"seafile.ccnetweb",
         "NSHumanReadableCopyright":u"Copyright © 2012 海文互知. All rights reserved.",
         "CFBundleVersion":"0.9.4"}
OPTIONS = {"argv_emulation": True, "packages":PACKAGES, "includes":INCLUDES,
           "excludes":EXCLUDES, "plist":PLIST }


destdir = "dist/ccnetweb.app/Contents/Resources/"

try:
    shutil.rmtree("dist")
    shutil.rmtree("build")
    shutil.copy("main.py", targetfile)
except Exception, e:
    pass    


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)


shutil.copytree("i18n", destdir + "i18n")
shutil.copytree("static", destdir + "static")
shutil.copytree("templates", destdir + "templates")
